.TS
allbox ;
c c c.
a	a	a
.TE

.TS
allbox ;
c s s s
c s c s
c c c c.
Title
sub 	sub
a	a	a	a
a	a	a	a
.TE

.TS
allbox tab(|);
c c c.
a | a | a
.TE

.TS
allbox tab(|);
c s s
c r c.
title
T{
aaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaa
T}| a | a
.TE


.TS
allbox expand tab(|);
c c c.
a | a | a
.TE

.TS
center tab(|);
c c c.
a | a | a
.TE

.TS
box tab(|);
c c c.
a | a | a
.TE

.TS
tab(|);
c c c.
a | a | a
.TE

.TS
expand tab(|);
c c c.
a | a | a
.TE
